apiVersion: v1
kind: Service
metadata:
  name: wordpress-php
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
  ports:
  - port: 80               # 3
    protocol: TCP          # 4
    targetPort: 80 
---
apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress-php
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1                                   
      maxSurge: 1  
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress-php
#        env:
#        - name: WORDPRESS_DB_HOST
#          value: wordpress-mysql
#        - name: WORDPRESS_DB_PASSWORD
#          value: asdf3wfAd!
        ports:
        - containerPort: 80
          name: wordpress-php