# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.10"
  config.vm.network "public_network"
  # config.vm.synced_folder "../data", "/vagrant_data"


  config.vm.provider "hyperv" do |h|
  h.vm_integration_services = {
    guest_service_interface: true,
    time_synchronization: true
  }
  h.memory = 1024
  h.vmname = "lamp"
  end
  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install software-properties-common
  # SHELL
  #config.vm.provision "ansible_local" do |ansible|
  #  ansible.playbook = "lamp.yml"
  #end
  #  config.vm.provision "ansible_local" do |ansible|
  #  ansible.playbook = "user.yml"
  #end
end
