apiVersion: extensions/v1beta1
kind: Deployment                                          # 1
metadata:
  name: cs-frontend
spec:
  replicas: 2                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate: 
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:                                               # 6
    metadata:
      labels:
        app: cs-frontend                                  # 7
    spec:
      containers:
        - image: wordpress
          imagePullPolicy: Always                         # 8
          name: cs-frontend
          ports:
            - containerPort: 80